export const FETCHERRORS = 'FETCHERRORS';
export const GETCATEGORIES = "GETCATEGORIES";
export const GETCUSTOMERS = "GETCUSTOMERS";
export const GETSUPPLIERS = "GETSUPPLIERS";
export const GETPRODUCTS = "GETPRODUCTS";